[package]
name = "contrast_render_engine"
version = "0.1.0"
authors = ["Alexander Meißner <AlexanderMeissner@gmx.net>"]
edition = "2018"

[features]
default = ["text"]
text = ["ttf-parser"]

[dependencies]
wgpu = "0.7.0"
ttf-parser = { version = "0.10.0", optional = true }
glam = "0.12.0"



### Showcase Example ###

[dev-dependencies]
winit = { version = "0.24.0", features = ["web-sys"] }
log = "0.4"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
async-executor = "1.0"
pollster = "0.2"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2.69"
web-sys = "0.3.46"
js-sys = "0.3.46"
wasm-bindgen-futures = "0.4.19"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
